services:
  hyperf-skeleton-service:
    container_name: hyperf-skeleton-service
    image: hyperf/hyperf:8.3-alpine-v3.22-swoole
    volumes:
      - ./:/srv
    ports:
      - "9501:9501"   # HYPERF
    environment:
      TZ: "America/Sao_Paulo"
      APP_ENV: dev
      SCAN_CACHEABLE: "false"
      REDIS_HOST: "hyperf-skeleton-redis"
      DB_HOST: "hyperf-skeleton-mysql"
      DB_DATABASE: "hyperf-skeleton-db"
      DB_USERNAME: "hyperf-skeleton-user"
      DB_PASSWORD: "secret"
      MAIL_MAILER: "smtp"
      MAIL_HOST: "hyperf-skeleton-smtp"
      MAIL_PORT: "1025"
      MAIL_FROM_ADDRESS: "no-reply@tecnofit.local"
      MAIL_FROM_NAME: "TecnoFit PIX"
    working_dir: /srv
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    depends_on:
      - hyperf-skeleton-mysql
      - hyperf-skeleton-redis
      - hyperf-skeleton-smtp
  hyperf-skeleton-mysql:
    container_name: hyperf-skeleton-mysql
    image: mysql:8
    volumes:
      - mariadb_volume:/var/lib/mysql
    ports:
      - "3307:3306"   # MYSQL
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "hyperf-skeleton-user"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "hyperf-skeleton-db"
  hyperf-skeleton-redis:
    container_name: hyperf-skeleton-redis
    image: redis:latest
    volumes:
      - redis_volume:/data    
    ports:
      - "6379:6379"   # REDIS
    restart: unless-stopped
  hyperf-skeleton-smtp:
    image: axllent/mailpit:latest
    container_name: hyperf-skeleton-smtp
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI Web

networks:
  default:
    name: hyperf-skeleton-network

volumes:
  mariadb_volume:
    driver: local  
  redis_volume:
    driver: local
